apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shop
  labels:
    app: backend
    component: api
spec:
  # ClusterIP — backend dostępny tylko wewnątrz klastra
  # Frontend proxy i Ingress kierują ruch przez frontend nginx
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
