apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shop
  labels:
    app: redis
    component: cache
spec:
  # ClusterIP — dostępny tylko wewnątrz klastra, NIE wystawiony na zewnątrz
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
