apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shop
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 200m      # prod: więcej zasobów
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
