apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: shop
  labels:
    app: postgres
    component: database
spec:
  # ClusterIP — dostępny tylko wewnątrz klastra, NIE wystawiony na zewnątrz
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
