apiVersion: v1
kind: Secret
metadata:
  name: shop-secret
  namespace: shop
type: Opaque
# UWAGA: wartości zakodowane w Base64 (nie szyfrowane!)
# Prawdziwe hasła produkcyjne NIE powinny być commitowane do repo
# W produkcji używać: Sealed Secrets, External Secrets Operator, Vault
# Kodowanie:  echo -n "haslo" | base64
data:
  DB_USER: c2hvcA==              # shop
  DB_PASS: c2hvcHBhc3N3b3JkMTIz # shoppassword123
  POSTGRES_USER: c2hvcA==        # shop
  POSTGRES_PASSWORD: c2hvcHBhc3N3b3JkMTIz # shoppassword123
  POSTGRES_DB: c2hvcA==          # shop
