apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shop
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 50m       # dev: mniejsze zasoby
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
